services:
  - type: web
    name: bunk3r-ia
    runtime: docker
    plan: starter
    envVars:
      - key: OLLAMA_URL
        value: "http://localhost:11434"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_IDhalvO17Apb@ep-wild-sea-advimph5-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: ALLOWED_WEB_ORIGIN
        value: "https://bunk3r-w3b.onrender.com" # CAMBIA ESTO POR TU URL REAL
      - key: FLASK_ENV
        value: production
    disk:
      name: ollama-data
      mountPath: /root/.ollama
      sizeGB: 10
